### ISSUE TITLE
DefaultResticFilter.txt

### ISSUE THREAD

**Issue by ch3810** [DavidKrGH/BackupScripts#3]
Hey, I have been looking through the repo as I like the way you have grouped things together, great project!

After testing the exclude functionality in restic, I believe the default filter example included may be misleading.

The example in your repo uses comments and the *.log line doesn't operate as expected. It seems that the whitepaces between the 'g' and '#' are counted as part of the exclude filter and so restic treats this as excluding any file with a .log extension + a bunch of spaces.

This may be worth modifying for convenience (even though it is more clearly shown in restic docs).

**Comment by DavidKrGH** [comment]
Hey, thank you very much for the kind words. Yes, you're absolutely right. I have adjusted the relevant parts. Thanks for the tip!
